export const UI_TEXT = {
  SECOND_HAND_STORE: 'SecondHand Store',
  HOME: 'Home',
  ABOUT: 'About',
  GO_HOME: 'Go Home',
  NEXT: 'Next',
  FINISH: 'Finish',
  BACK: 'Back',
  PRICE: 'Price',
  NAME: 'Name',
  FAILED_TO_LOAD_PRODUCTS: 'Failed to load products',
  REVIEWS: 'reviews',
  ADD_TO_CART: 'Add to Cart',
  MANAGER: 'Manager',
  CUSTOMER: 'Customer',
  ORDER: 'Orders',
  PRODUCTS: 'Products',
  CUSTOMERS: 'Customers',
  DASHBOARD: 'Dashboard',
  PROFILE: 'Profile',
  LOCKERS: 'Lockers',
  SUBTITLE1_VARIANT: 'subtitle1',
  SELECT_AN_OPTION: 'Select an option...',
  CART_TITLE: 'Shopping Cart',
  CART_EMPTY: 'Your cart is empty',
  CART_TOTAL: 'Total',
  CART_CONTINUE: 'Continue to Purchase',
  PRODUCT_NAME: 'Product Name',
  CART_LOADING: "Loading...",
  CART_LOGIN_REQUIRED: "Please log in to continue your purchase.",
  CART_ERROR: "Error loading cart. Please try again.",
};
