export const UI_TEXT = {
  SECOND_HAND_STORE: 'SecondHand Store',
  HOME: 'Home',
  ABOUT: 'About',
  GO_HOME: 'Go Home',
  NEXT: 'Next',
  FINISH: 'Finish',
  BACK: 'Back',
  PRICE: 'Price',
  NAME: 'Name',
  FAILED_TO_LOAD_PRODUCTS: 'Failed to load products',
  REVIEWS: 'reviews',
  ADD_TO_CART: 'Add to Cart',
  MANAGER: 'Manager',
  CUSTOMER: 'Customer',
  ORDER: 'Orders',
  PRODUCTS: 'Products',
  CUSTOMERS: 'Customers',
  DASHBOARD: 'Dashboard',
  PROFILE: 'Profile',
  LOCKERS: 'Lockers',
  SUBTITLE1_VARIANT: 'subtitle1',
  SELECT_AN_OPTION: 'Select an option...',
  CART_TITLE: 'Shopping Cart',
  CART_EMPTY: 'Your cart is empty',
  CART_TOTAL: 'Total',
  CART_CONTINUE: 'Continue to Purchase',
  PRODUCT_NAME: 'Product Name',
  CART_LOADING: 'Loading...',
  CART_LOGIN_REQUIRED: 'Please log in to continue your purchase.',
  CART_ERROR: 'Error loading cart. Please try again.',
  NEWEST_PRODUCTS: 'Newest Products',
  CART_REMOVE: 'Remove from Cart',
};

export const LOGIN_TEXT = {
  title: 'Login',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  submit: 'Login',
  emailRequired: 'Email is required',
  invalidEmail: 'Invalid email address',
  passwordRequired: 'Password is required',
  usernameLabel: 'Username',
  usernameRequired: 'Username is required',
};

export const SIGNUP_TEXT = {
  title: 'Sign Up',
  nameLabel: 'Full Name',
  usernameLabel: 'Username',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  confirmPasswordLabel: 'Confirm Password',
  submit: 'Create Account',

  nameRequired: 'Name is required',
  usernameRequired: 'Username is required',
  emailRequired: 'Email is required',
  invalidEmail: 'Please enter a valid email',
  passwordMin: 'Password must be at least 6 characters',
  passwordRequired: 'Password is required',
  confirmPasswordRequired: 'Please confirm your password',
  passwordMismatch: 'Passwords do not match',
};
